### ISSUE TITLE
Support initial loading of data

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph-docker#16]
We should make it easy to load data on startup, e.g., for integration tests. Many database images support loading of data from the `/docker-entrypoint-initdb.d/` directory (like [PostgreSQL](https://hub.docker.com/_/postgres#initialization-scripts), [MySQL](https://hub.docker.com/_/mysql#initializing-a-fresh-instance), or [MongoDB ](https://hub.docker.com/_/mongo#initializing-a-fresh-instance)). So that seems to be the de facto standard.
I think it makes sense to support the following formats:

- Groovy scripts can just be executed with the Gremlin Console
- GraphSON / Gryo files should be loaded, probably also with the Gremlin Console, maybe by connecting [with remote](http://tinkerpop.apache.org/docs/3.4.1/reference/#console-remote-console)

**Comment by rafaelcaricio** [comment]
Right now I'm mounting a custom script overwriting the `/opt/janusgraph/scripts/empty-sample.groovy` to load my initial data.

Example:
```yaml
version: "3.7"
services:
  janusgraph:
    image: janusgraph/janusgraph:0.3.1
    ports:
      - "8182:8182"
    volumes:
      - type: bind
        source: .
        target: /opt/my/data
      - type: bind
        source: ./load_data.groovy
        target: /opt/janusgraph/scripts/empty-sample.groovy
```

But would be great to have a better way to do this.
