### ISSUE TITLE
Miscellaneous Improvements: yq v4; TinkerIoRegistry; cross-platform build

### ISSUE THREAD

**Issue by phreed** [JanusGraph/janusgraph-docker#80]
I forked the  project and am working on several improvements.
https://github.com/babeloff/janusgraph-docker

I would like as many of these to make it into the main repo as possible.
Could I get some guidance on the best way to proceed?)

- [x] upgrade yq to v4.x
- [x] add TinkerIoRegistry to the gremlin-server.yaml
- [x] switch from bash scripts to Gradle 
- [x] remote-objects.yaml 

## YQ

The new version is much more capable than the prior.
This change leads to an overhaul of `docker-entrypoint.sh` and expansion of the configuration of docker environment variables e.g.  `gremlinserver.*`  -> `gremlinserver%1.*` (or something like that)

## TinkerIoRegistry

The ability to return subgraphs is not possible because the TinkerIoRegistryV3d0 is not included in the `gremlin-server.yaml`. 
This could be overcome with the yq update mentioned above. In the short run the following could be added.

```
serializers:
...
  - className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0
    config:
      ioRegistries:
        - org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry
        - org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerIoRegistryV3d0
...
```

## Gradle

bash is flaky on Windows.
Gradle works across platforms and has Docker plugins.

## remote-objects.yaml

It has the wrong host (localhost rather than janusgraph)
