### ISSUE TITLE
Unable to access /var/lib/janusgraph permission denied

### ISSUE THREAD

**Issue by winaterion** [JanusGraph/janusgraph-docker#86]
Janus container version: 0.5.3.
I am using Kubernetes yaml file to configure pre populated database files.
In order to do so, I run the following:
```
mkdir /var/lib/janusgraph/data
mkdir /var/lib/janusgraph/index
tar -xzf /mnt/kb-data/janusgraph-be.tar.gz -C /var/lib/janusgraph
```

but container is failing with error that I do not have permission for _/var/lib/janusgraph folder_
This code used to work before, but I know that permission handling was changed, and I guess this is the result.

I see in your dockerfile that you set:
    `useradd -r -g janusgraph --uid=999 -d ${JANUS_DATA_DIR} janusgraph && \`
and also 
`    chown -R janusgraph:janusgraph ${JANUS_HOME} ${JANUS_INITDB_DIR} ${JANUS_CONFIG_DIR} ${JANUS_DATA_DIR}
`
so I wonder why I can't access this folder. 

Note: I do have access to /opt/janusgraph/ but not /var/lib/janusgraph

here is my some parts of the kubernetes yaml:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: janusgraph-test2
  labels:
    app: janusgraph-test2
spec:
  serviceName: janusgraph-service-test2
  replicas: 1
  selector:
    matchLabels:
      app: janusgraph-test2
  template:
    metadata:
      labels:
        app: janusgraph-test2
    spec:
      containers:
        - name: janusgraph-test2
          image: janusgraph/janusgraph:0.5.3
          env:
          - name: JAVA_OPTIONS
            value: "-javaagent:/var/lib/janusgraph/jmx_prometheus_javaagent-0.13.0.jar=8090:/var/lib/janusgraph/config.yml"
          - name: janusgraph.query.force-index
            value: "true"
          - name: janusgraph.storage.read-only
            value: "true"
          - name: janusgraph.storage.berkeleyje.lock-mode
            value: "LockMode.READ_UNCOMMITTED"
          - name: gremlinserver.channelizer
            value: "org.apache.tinkerpop.gremlin.server.channel.WsAndHttpChannelizer"
          - name: gremlinserver.maxContentLength
            value: "1048576"
          - name: gremlinserver.writeBufferHighWaterMark
            value: "1048576"
          - name: janusgraph.storage.berkeleyje.cache-percentage
            value: "80"
          - name: janusgraph.cache.db-cache
            value: "true"
          - name: janusgraph.cache.db-cache-clean-wait
            value: "10000"
          - name: janusgraph.graph.replace-instance-if-exists
            value: "true"

          command: 
          - /bin/bash 
          - "-c" 
          - |
            set -ex
            if [[ ! -d /var/lib/janusgraph/data ]]; then
                mkdir /var/lib/janusgraph/data
                mkdir /var/lib/janusgraph/index
                tar -xzf /mnt/kb-data/janusgraph-be.tar.gz -C /var/lib/janusgraph
                cp /mnt/kb-data/jmx_prometheus_javaagent-0.13.0.jar /var/lib/janusgraph
                cp /mnt/kb-data/config.yml /var/lib/janusgraph
                echo "KB-Data populated $(date)"
            fi 
            sed -i 's/consoleReporter: {enabled: true/consoleReporter: {enabled: false/' /opt/janusgraph/conf/gremlin-server/gremlin-server.yaml
            sed -i 's/csvReporter: {enabled: true/csvReporter: {enabled: false/' /opt/janusgraph/conf/gremlin-server/gremlin-server.yaml
            sed -i 's/slf4jReporter: {enabled: true/slf4jReporter: {enabled: false/' /opt/janusgraph/conf/gremlin-server/gremlin-server.yaml
            sed -i 's/jmxReporter: {enabled: false/jmxReporter: {enabled: true/' /opt/janusgraph/conf/gremlin-server/gremlin-server.yaml
            grep -qxF 'graph.replace-instance-if-exists=true' /opt/janusgraph/conf/janusgraph-inmemory.properties || echo 'graph.replace-instance-if-exists=true' >> /opt/janusgraph/conf/janusgraph-inmemory.properties
            docker-entrypoint.sh janusgraph

```

**Comment by farodin91** [comment]
Did you mount a folder which does not have the correct permissions?

```
docker run --rm -it janusgraph/janusgraph:0.5.3 bash    
janusgraph@4a363f8719d1:/opt/janusgraph$ ls -lia
total 88
993784 drwxr-xr-x. 1 janusgraph janusgraph  4096 Mar 28 20:26 .
993783 drwxr-xr-x. 1 root       root        4096 Mar 28 20:26 ..
978750 -rw-rw-r--. 1 janusgraph janusgraph 31560 Dec  3 23:25 LICENSE.txt
978751 -rw-rw-r--. 1 janusgraph janusgraph  4751 Dec 25 13:38 NOTICE.txt
993785 drwxrwxr-x. 1 janusgraph janusgraph  4096 Dec 25 13:38 bin
993786 drwxrwxr-x. 1 janusgraph janusgraph  4096 Dec 25 13:38 conf
993791 drwxrwxr-x. 1 janusgraph janusgraph  4096 Dec 25 13:38 data
993792 drwxrwxr-x. 1 janusgraph janusgraph  4096 Dec  3 23:24 ext
993793 drwxr-xr-x. 1 janusgraph janusgraph 20480 Dec 25 13:53 lib
993794 drwxrwxr-x. 1 janusgraph janusgraph  4096 Mar 28 20:26 scripts
janusgraph@4a363f8719d1:/opt/janusgraph$ cd /var/log/
alternatives.log  apt/              btmp              dpkg.log          faillog           lastlog           wtmp              
janusgraph@4a363f8719d1:/opt/janusgraph$ cd /var/lib/janusgraph/
janusgraph@4a363f8719d1:~$ ls -lia
total 8
993801 drwxr-xr-x. 2 janusgraph janusgraph 4096 Mar 28 20:26 .
993800 drwxr-xr-x. 1 root       root       4096 Mar 28 20:26 ..
janusgraph@4a363f8719d1:~$ 
```

**Comment by winaterion** [comment]
You are totaly right, I do have a mount point:
```
          volumeMounts:
            - name: data
              mountPath: /var/lib/janusgraph
```
The reason I have this mount point is because I need a big volume for janush data.
So, since you mentioned that, I know added permission to my Kubernetes yaml:

```
    ....
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: janusgraph-test2
          image: janusgraph/janusgraph:0.5.3
          env:
          - name: JAVA_OPTIONS
         ...
         ...
```
And now my scripts inside the yaml works, but docker-entrypoint.sh is showing an alarming message:
**_+ docker-entrypoint.sh janusgraph
chown: changing ownership of '/var/lib/janusgraph/lost+found': Operation not permitted
chown: changing ownership of '/var/lib/janusgraph': Operation not permitted
chmod: changing permissions of '/var/lib/janusgraph': Operation not permitted_**

How would I overcome this one (although the container is running fine now, and not crashing)

**Comment by winaterion** [comment]
OK, so the final fix is to actually use initcontainer to change the permissions (because you can't set user permission via kubernetes yaml in a normal way).
here is the hack:

```
      initContainers:
      - name: volume-mount-hack
        image: openjdk:8-jre-slim-buster
        command: ["sh", "-c", "chown -R 999:999 /var/lib/janusgraph"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/janusgraph
```
